- name: check if selinux is running and enforced
  command: getenforce
  register: sestatus
  changed_when: false

- name: Check SELinux
  assert:
    that:
      - "sestatus.stdout == 'Enforcing'"
    msg: "Please set SELinux to Enforcing"
