

- set_fact:
    newline: "\n"
- copy:
    content: "{{ repos | sort | join('\n') }}\n"
    dest: /tmp/stc-repos-should-enabled

- shell: "subscription-manager repos --list-enabled | grep 'Repo ID'  | cut -f2 -d':' | tr -d ' ' | sort > /tmp/stc-repos-enabled"
  args:
    creates: /tmp/stc-repos-enabled

- shell: "diff -Nuar /tmp/stc-repos-should-enabled /tmp/stc-repos-enabled"
  ignore_errors: true
  register: ret


- assert:
    that:
      - "ret.rc == 0"
    msg: 
      - "Please check enabled repositories"
      - "{{ ret.stdout_lines }}"

- name: Cleanup tmp files
  file:
    state: absent
    path: "{{ item }}"
  with_items: 
  - /tmp/stc-repos-should-enabled
  - /tmp/stc-repos-enabled
  tags:
  - cleanup
