---
- name: Collect information about subscription and remote user
  hosts: localhost
  gather_facts: no
  vars_files:
  - "{{file_env}}"
  tasks:
  - name: Create key for remote user
    user:
      name: "{{ssh_user}}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
- name: Distribute public keys and populate known_hosts
  gather_facts: no
  hosts: all
  vars_files:
  - "{{file_env}}"
  tasks:
  - name: Add key to authorized_keys
    authorized_key:
      user: "{{ssh_user}}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  - name: Fetch hostkey
    connection: local
    command: "ssh-keyscan {{ inventory_hostname }}"
    register: hostkey
  - name: Run ssh-keyscan to add keys to known_hosts
    connection: local
    known_hosts:
      name: "{{ inventory_hostname }}"
      key: "{{ item }}"
    with_items: "{{ hostkey.stdout_lines }}"
    when: hostkey.rc == 0
